export default [
  "Way of the Househusband",
  "One Punch Man",
  "Wanpanman",
  "Mushoku Tensei",
  "Jobless Reincarnation",
  "That time i got reincarnated as a slime",
  "Slime Datta ken",
  "Baki hanma",
  "Demon Slayer",
  "Kimetsu no Yaiba",
  "Dr Stone",
  "The Devil Is a Part-Timer",
  "HATARAKU MAOU-SAMA!",
  "Way of the Househusband",
  "KONO SUBARASHI",
  "Trapped in a dating sim",
  "Otome Game Sekai wa Mob ni Kibishii Sekai desu",
  "My dress up darling",
  "SONO BISQUE DOLL WA KOI WO SURU",
  "Spy X Family",
  "World Trigger",
  "Our last crusade",
  "Kimisen boku",
  "Busou Shoujo Machiavellianism",
  "ReLife",
  "Kage no Jitsuryokusha ni Naritakute!",
];
